on:
  workflow_call:
    inputs:
      unity-version:
        required: true
        type: string
      api-level:
        required: true
        type: string

jobs:
  # needs.try-*.outputs.status == 'failed' => Smoke test failed, no need to retry.
  # needs.try-*.result == 'failure'        => CI Setup failed.
  try-1:
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 1

  try-1-check-failed:
    runs-on: ubuntu-latest
    needs: [try-1]
    steps:
      - name: Check failed
        run: |
          if [[ "${{ needs.try-1.outputs.status }}" == "failed" ]]; then
            echo "Smoke test failed."
            exit 0 # change to 0 later.
          fi

  try-2:
    needs: [try-1-check-failed]
    if: ${{ needs.try-1.result == 'failure' || needs.try-1.outputs.status != 'success' }}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 2      

  try-2-check-failed:
    runs-on: ubuntu-latest
    needs: [try-2]
    steps:
      - name: Check failed
        run: |
          if [[ "${{ needs.try-2.outputs.status }}" == "failed" ]]; then
            echo "Smoke test failed."
            exit 0 # change to 0 later.
          fi

  try-3:
    needs: [try-2-check-failed]
    if: ${{ needs.try-2.result == 'failure' || needs.try-1.outputs.status != 'success' }}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 3

  try-3-check-status:
    runs-on: ubuntu-latest
    needs: [try-3]
    steps:
      - name: Check final result
        run: |
          if [[ "${{ needs.try-3.outputs.status }}" == "flaky" || "${{ needs.try-3.outputs.status }}" == "crashed" ]]; then
            echo "Job status is flaky or crashed. Exiting with code 78."
            exit 78
          fi
          if [[ "${{ needs.try-2.outputs.status }}" == "failed" ]]; then
            echo "Smoke test failed."
            exit 0 # change to 0 later.
          fi