on:
  workflow_call:
    inputs:
      unity-version:
        required: true
        type: string
      api-level:
        required: true
        type: string

jobs:
  try-1:
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 1
  show-status:
    runs-on: ubuntu-latest
    needs: try-1
    steps:
      - name: Get status from smoke test workflow
        run: echo "The status from the smoke test is ${{ needs.try-1.outputs.status }}"

  try-2:
    needs: [try-1]
    if: ${{ needs.try-1.outputs.status == 'failure' }}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 2

  try-3:
    needs: [try-2]
    if: ${{ needs.try-2.outputs.status == 'failure' }}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 3
