on:
  workflow_call:
    inputs:
      unity-version:
        required: true
        type: string
      api-level:
        required: true
        type: string

jobs:
  try-1:
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 1

  try-2:
    needs: [try-1]
    # needs.try-1.result == 'failure' checks Emulator Setup
    # needs.try-1.outputs.status == 'flaky' checks Smoke test flakyness.
    if: ${{ needs.try-1.result == 'failure' || needs.try-1.outputs.status == 'flaky' || needs.try-1.outputs.status == 'failed'}}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 2

  try-3:
    needs: [try-2]
    if: ${{ needs.try-2.result == 'failure' || needs.try-2.outputs.status == 'flaky' || needs.try-2.outputs.status == 'failed'}}
    uses: ./.github/workflows/android-smoke-test.yml
    with:
      unity-version: ${{ inputs.unity-version }}
      api-level: ${{ inputs.api-level }}
      try: 3
  
  result:
    runs-on: ubuntu-latest
    needs: [try-1, try-2, try-3]
    steps:
      - name: Try-Result
        run: |
          try_3_status="${{ needs.try-3.outputs.status || 'not_run' }}"
          try_2_status="${{ needs.try-2.outputs.status || 'not_run' }}"
          try_1_status="${{ needs.try-1.outputs.status || 'not_run' }}"

          if [[ "${{ try_3_status }}" == "flaky" || "${{ try_2_status }}" == "crashed" ]]; then
            echo "Skipping due to flaky or crashed status."
            exit 78
          elif [[ "${{ try_3_status }}" == "success" || "${{ try_2_status }}" == "success" || "${{ try_1_status }}" == "success" ]]; then
            echo "Exiting with code 0 due to success."
            exit 0
          else
            echo "Exiting with code 1."
            exit 1
          fi

