name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

jobs:
  build:
    name: Unity ${{ matrix.unity-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        api-level: [21]
        # 2022.1.0a12 removed until S.T.J issues fixed
        include:
          - os: macos-latest
    steps:
      # Tag: 0.9.1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - name: "Set up Java: 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore previous build
        uses: actions/cache@v2
        with:
          path: samples/artifacts/builds
          # using hash of package.json to bust cache on release builds which modify it
          key: ${{ matrix.os }}-${{ matrix.unity-version }}-${{ matrix.unity-version-changeset }}-${{ hashFiles('package/package.json') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Setup Android Emulators
        if: matrix.os == 'macos-latest'
        uses: reactivecircus/android-emulator-runner@v2
        with:          
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Run Smoke Tests (Android)
        if: matrix.os == 'macos-latest'
        shell: pwsh
        run: ./scripts/smoke-test-droid.ps1
