name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

jobs:
    
  build:
    name: Unity
    runs-on: macos-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      # Tag: 0.9.1
      - name: Test1
        shell: pwsh
        run: |
          echo "unity_path2=C:\ bla bla" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Output "Unity path is $env:unity_path2"

      - name: Test2
        shell: pwsh
        run: |
          xcrun simctl list devices
        
      - name: Preparing test app for smoke test.
        uses: actions/upload-artifact@v2
        with:
          name: droid-testapp-aa
          path: scripts/app.apk
