name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

jobs:
    
  build:
    name: Unity
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # 2022.1.0a12 removed until S.T.J issues fixed
        unity-version: [2019.4.31f1]
        include:
          - os: windows-latest
            unity-installation-path: C:/Program Files/Unity/
            unity-root: C:/Program Files/Unity/Hub/Editor/
            unity-path: Editor/
            unity-config-path: C:/ProgramData/Unity/config/
          - os: macos-latest
            unity-installation-path: /Applications/Unity/
            unity-root: /Applications/Unity/Hub/Editor/
            unity-path: Unity.app/Contents/MacOS
            unity-config-path: /Library/Application Support/Unity/config/
          - unity-version: 2019.4.31f1
            unity-version-changeset: bd5abf232a62
          - unity-version: 2020.3.21f1
            unity-version-changeset: a38c86f6690f
          - unity-version: 2021.1.26f1
            unity-version-changeset: 6f076387c01d
          # - unity-version: 2022.1.0a12
          #   unity-version-changeset: 816252c3efbb

    steps:
      # Tag: 0.9.1
      - name: Test1
        shell: pwsh
        run: |
          $env:unity_path2 = "ABC";
          Write-Output "Unity path is $env:unity_path2"

      - name: Test2
        shell: pwsh
        run: |
          Write-Output "Unity path was $env:unity_path2"
          $env:unity_path2 = "DEF";
          Write-Output "Unity path is $env:unity_path2"
        
      - name: Preparing test app for smoke test.
        uses: actions/upload-artifact@v2
        with:
          name: droid-testapp-aa
          path: scripts/app.apk

  android-smoke-test:
    needs: [build]
    name: Smoke Test - Android ${{ matrix.api-level }} Unity ${{ matrix.unity-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
         api-level: [27, 22, 23, 24, 25, 26, 21, 28, 29]
         #api-level 30 image is only available with google services.
         unity-version: [2019.4.31f1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.unity-version }}-22

      - name: Smoke test
        uses: reactivecircus/android-emulator-runner@2b2ebf2e518e38a17180117fc2b677006db27330
        with:
         api-level: ${{ matrix.api-level }}
         force-avd-creation: false
         emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
         disable-animations: false
         script: pwsh ./scripts/smoke-test-droid.ps1

  android-smoke-test-with-gservices:
    needs: [build]
    name: Smoke Test - Android ${{ matrix.api-level }} Unity ${{ matrix.unity-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
         api-level: [30]
         #api-level 30 image is only available with google services.
         unity-version: [2019.4.31f1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.unity-version }}-gservices-22

      - name: Smoke test
        uses: reactivecircus/android-emulator-runner@2b2ebf2e518e38a17180117fc2b677006db27330
        with:
         api-level: ${{ matrix.api-level }}
         target: google_apis
         force-avd-creation: false
         emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
         disable-animations: false
         script: pwsh ./scripts/smoke-test-droid.ps1
