name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

jobs:
    
  build:
    name: Unity
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # 2022.1.0a12 removed until S.T.J issues fixed
        unity-version: [2019.4.31f1]
        include:
          - os: macos-latest
            unity-installation-path: /Applications/Unity/
            unity-root: /Applications/Unity/Hub/Editor/
            unity-path: Unity.app/Contents/MacOS
            unity-config-path: /Library/Application Support/Unity/config/
          - unity-version: 2019.4.31f1
            unity-version-changeset: bd5abf232a62
          - unity-version: 2020.3.21f1
            unity-version-changeset: a38c86f6690f
          - unity-version: 2021.1.26f1
            unity-version-changeset: 6f076387c01d
          # - unity-version: 2022.1.0a12
          #   unity-version-changeset: 816252c3efbb

    steps:
      # Tag: 0.9.1
      - name: Test1
        shell: pwsh
        run: |
          echo "unity_path2=C:\ bla bla" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Output "Unity path is $env:unity_path2"

      - name: Test2
        shell: pwsh
        run: |
          xcrun simctl list devices
        
      - name: Preparing test app for smoke test.
        uses: actions/upload-artifact@v2
        with:
          name: droid-testapp-aa
          path: scripts/app.apk
