name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-android-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Android Smoke Test Wrapper
        uses: ./android-smoke-test-wrapper.yml
        with:
          unity-version: 666
          api-level: 28
